# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_auto_20180720_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttemptedQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizStatus', models.CharField(max_length=200)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='users',
            field=models.ManyToManyField(through='polls.UserAttemptedQuiz', to=settings.AUTH_USER_MODEL),
        ),
    ]
